# Generated by Django 4.2.17 on 2026-05-25 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='users.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('ingestion_run', 'row_index')},
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant', 'name')},
        ),
    ]
