# Generated by Django 4.2.17 on 2026-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct Emissions'), ('SCOPE_2', 'Scope 2 — Indirect (Energy)'), ('SCOPE_3', 'Scope 3 — Other Indirect')], max_length=20)),
                ('category', models.CharField(help_text='e.g. stationary_combustion, purchased_electricity, air_travel', max_length=100)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(help_text='Original unit e.g. liters, kWh, km', max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, help_text='Emission quantity in kgCO2e', max_digits=18)),
                ('unit_normalized', models.CharField(default='kgCO2e', help_text='Always kgCO2e', max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('emission_factor_source', models.CharField(help_text='e.g. DEFRA 2023, CEA 2022', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('facility_code', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('flagged_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emission entries',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
    ]
